    - name: Run Main Workflow
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        # Alttaki 2 satırı ekledik ki kod dosyaları bulabilsin
        PYTHONPATH: .
        CI: "true"
      run: |
        echo '${{ secrets.YOUTUBE_TOKEN }}' > token.json
        echo '${{ secrets.YOUTUBE_CLIENT_SECRET }}' > client_secret.json
        python main.py
